export const productsData = [
  {
    id: 1,
    image: "/headPhone.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
  {
    id: 2,
    image: "/t-shirt.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
  {
    id: 3,
    image: "/water_bottle.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
  {
    id: 4,
    image: "/headPhone.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
  {
    id: 5,
    image: "/t-shirt.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
  {
    id: 6,
    image: "/water_bottle.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
  {
    id: 7,
    image: "/t-shirt.png",
    off: "22%",
    title: "Soft Newborn Baby Wrap Blankets Baby Sleeping ",
    price: "1920",
    originPrice: "3000",
  },
];
